#!/bin/bash

# This is the init script for the StreamNet daemon.
# When deployed, it should be placed under /etc/init.d/
# to be executed as a service.

[ -z "$STREAMNET_HOME" ] && STREAMNET_HOME="/opt/streamnet/"

LIB_DIR=$STREAMNET_HOME/lib
CONF_DIR=$STREAMNET_HOME/conf


CLASSPATH=$CONF_DIR
CLASSPATH=$CLASSPATH:$(echo $LIB_DIR/*.jar | tr ' ' ':')
CLASSPATH=$CLASSPATH:$STREAMNET_HOME/StreamNet.jar
CLASSPATH=$CLASSPATH:/opt/hadoop-2.6.0/etc/hadoop:/opt/hadoop-2.6.0/share/hadoop/common/lib2/*:/opt/hadoop-2.6.0/share/hadoop/common/*:/opt/hadoop-2.6.0/share/hadoop/hdfs:/opt/hadoop-2.6.0/share/hadoop/hdfs/lib/*:/opt/hadoop-2.6.0/share/hadoop/hdfs/*:/opt/hadoop-2.6.0/share/hadoop/yarn/lib/*:/opt/hadoop-2.6.0/share/hadoop/yarn/*:/opt/hadoop-2.6.0/share/hadoop/mapreduce/lib/*:/opt/hadoop-2.6.0/share/hadoop/mapreduce/*:/contrib/capacity-scheduler/*.jar
PIDFILE=/tmp/streamnet.pid

start() {
    [ -f $PIDFILE ] && echo "StreamNet already running ($(cat $PIDFILE))" && exit 0
    java -Dname=StreamNet -cp $CLASSPATH  gr.ntua.cslab.streamnet.Main &
    echo $! > $PIDFILE;
}

stop() {
    PID=$(cat $PIDFILE 2>/dev/null)
    [ "$PID" == "" ] && echo "StreamNet not running" && exit 0
    kill -TERM $PID
    rm -f $PIDFILE
}

status() {
    if [ -f $PIDFILE ]; then
        PID=$(cat $PIDFILE)
        echo "StreamNet running ($PID)"
    else
        echo "StreamNet not running"
    fi
}

case $1 in
    start)
        start;
    ;;
    stop)   
        stop;
    ;;
    restart)    
        stop && start;
    ;;
    status)   
        status;
    ;;
    *)      
        echo "$0 {start|stop|status|restart}"
    ;;
esac

