add jar diplom.jar;
create temporary function GetAS as 'diplom.GetAS';
add file /data/GeoIPASNum2.csv;
INSERT OVERWRITE LOCAL DIRECTORY 'outputs/topASPairs_full_shark' ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n'
SELECT getas(ipfrom, './GeoIPASNum2.csv'), getas(ipto, './GeoIPASNum2.csv'), COUNT(*) AS pairs 
FROM sflows
GROUP BY getas(ipfrom, './GeoIPASNum2.csv'), getas(ipto, './GeoIPASNum2.csv') 
ORDER BY pairs DESC;
