add jar diplom.jar;
create temporary function GetCountry as 'diplom.GetCountry';
add file /data/GeoIPCountryWhois.csv;
INSERT OVERWRITE LOCAL DIRECTORY 'outputs/topCountriesOutgoing_full' ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n'
SELECT getcountry(ipfrom, './GeoIPCountryWhois.csv'), COUNT(*) AS outgoing 
FROM sflows
GROUP BY getcountry(ipfrom, './GeoIPCountryWhois.csv')
ORDER BY outgoing DESC;
